CREATE TABLE BANK_DATA (
    id INT PRIMARY KEY,
    address_state VARCHAR(2),
    application_type VARCHAR(50),
    emp_length INT,
    emp_title VARCHAR(100),
    grade CHAR(1),
    home_ownership VARCHAR(20),
    issue_date DATE,
    last_credit_pull_date DATE,
    last_payment_date DATE,
    loan_status VARCHAR(20),
    next_payment_date DATE,
    member_id INT,
    purpose VARCHAR(50),
    sub_grade CHAR(2),
    term VARCHAR(20),
    verification_status VARCHAR(20),
    annual_income DECIMAL(10, 2),
    dti DECIMAL(5, 2),
    installment DECIMAL(10, 2),
    int_rate DECIMAL(5, 2),
    loan_amount DECIMAL(10, 2),
    total_acc INT,
    total_payment DECIMAL(15, 2)
);
